name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
env:
   
jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneWindows: "Turkey Standard Time"
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore CodeApp.Oracle.sln

      - name: Build Solution
        run: |
          msbuild.exe CodeApp.Oracle.sln /property:Configuration=Release
        
      - name: Run Unit Tests
        run: vstest.console.exe .\CodeApp.Oracle.Tests\bin\Release\CodeApp.Oracle.Tests.dll