name: "Deploy to NuGet"

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'

env:
  COMMON_PROJECT_PATH: 'CodeApp.Common/CodeApp.Common.csproj' 
  DB_PROJECT_PATH: 'CodeApp.DB/CodeApp.DB.csproj'  
  EMAIL_PROJECT_PATH: 'CodeApp.Email/CodeApp.Email.csproj'  
  UNITTEST_COMMON_PROJECT_PATH: 'CodeApp.Common.Tests/bin/Release/CodeApp.Common.Tests.dll'
  UNITTEST_DB_PROJECT_PATH: 'CodeApp.DB.Tests/bin/Release/CodeApp.DB.Tests.dll'  
  UNITTEST_EMAIL_PROJECT_PATH: 'CodeApp.Email.Tests/bin/Release/CodeApp.Email.Tests.dll'  
  SOLUTION_PATH: 'CodeApp.Common.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    - name: Setup Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneWindows: "Turkey Standard Time"

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'   
     
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5
        
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1      
      
    - name: Restore nuget packages
      run: nuget restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: msbuild ${{ env.SOLUTION_PATH }} /p:Configuration=Release
      
    - name: Run CodeApp.Common Unit Tests
      run: vstest.console.exe  ${{ env.UNITTEST_COMMON_PROJECT_PATH }}
      
    - name: Run CodeApp.DB Unit Tests
      run: vstest.console.exe  ${{ env.UNITTEST_DB_PROJECT_PATH }}
      
    - name: Run CodeApp.Email Unit Tests
      run: vstest.console.exe  ${{ env.UNITTEST_EMAIL_PROJECT_PATH }}

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
     
    - name: 'Pack CodeApp.Common project'
      run: nuget pack ${{ env.COMMON_PROJECT_PATH }} -Properties Configuration=Release -OutputDirectory ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Version 1.0.${{ github.run_number }}
     
    - name: 'Pack CodeApp.DB project'
      run: nuget pack ${{ env.DB_PROJECT_PATH }} -Properties Configuration=Release -OutputDirectory ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Version 1.0.${{ github.run_number }}
      
    - name: 'Pack CodeApp.Email project'
      run: nuget pack ${{ env.EMAIL_PROJECT_PATH }} -Properties Configuration=Release -OutputDirectory ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -Version 1.0.${{ github.run_number }}

    - name: 'Push all of packages'
      run: nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg  ${{ secrets.NUGET_AUTH_TOKEN }} -Source ${{ env.NUGET_SOURCE_URL }}
   


    
